FROM python:3.6-slim

RUN echo 'Dockerfile-CeleryBeat'

RUN mkdir /app
WORKDIR /app
COPY . /app

RUN pip install -U pip
RUN pip install -r requirements.txt

ENTRYPOINT celery -A app.tasks:celery beat --loglevel=info